/**
 * Template generated by vue-cli
 * https://github.com/webartisans-es/vue-component
 *
 * Component {{name}}
 * @author {{author}}
 */

export default {
	/**
	 * Name of the component
	 */
	name: '{{name}}',

	/**
	 * The attributes of this component
	 * @returns Object
	 */
	data() {
		return {
		}
	},

	mounted() {
	}
}