<!--
* Template generated by vue-cli:
* https://github.com/webartisans-es/vue-component
*
* Component {{name}}
* @author {{author}}
-->

<!--Template-->
<template src="./{{capitalize name}}.html"></template>
<!--Script-->
<script src="./{{capitalize name}}.{{#script}}{{../script}}{{else}}js{{/script}}" {{#script}}lang="{{../script}}"{{/script}}></script>
<!--Style-->
<style src="./{{capitalize name}}.{{#style}}{{../style}}{{else}}css{{/style}}" {{#style}}lang="{{../style}}"{{/style}} scoped></style>