###
  Template generated by vue-cli
  https://github.com/webartisans-es/vue-component

  Component {{name}}
  @author {{author}}
###


class {{name}}

###
Name of the component
###
name: '{{name}}'

###
  The attributes of this component
   @returns Object
###
data: () =>
  return {
  }


###
  The Component is mounted to the DOM
###
mounted: () =>
  console.log "{{name}} is ready"


module.export = new { {name}
}